services:
  demo-showcase:
    image: demo-showcase:latest
    build: .
    ports:
      - "4545:80"
    restart: unless-stopped
    volumes:
      - ./public/demos.json:/usr/share/nginx/html/demos.json:ro
